### ISSUE TITLE
Schema Updates

### ISSUE THREAD

**Issue by 12wollmana** [12wollmana/UMN-Data_Analytics-Project_02#18]
Split Date column into Year, Month, Day, Hour columns in the Case table.

**Comment by willhwh** [comment]
1. role column in the subject table is too short to store certain values.
2. resistance column in the subject table cannot store a null value.
3. race column in the subject table cannot store a null value.
4. sex column in the subject table is too short to store "not recorded."
5. case number in the case table is too short to store certain values.

**Comment by 12wollmana** [comment]
Finished making the updates.  All CSV files are able to be imported.
