### ISSUE TITLE
Case to City ID Link Not Setup in Tables

### ISSUE THREAD

**Issue by 12wollmana** [12wollmana/UMN-Data_Analytics-Project_02#28]
When testing out my API, there isn't a link setup between the case to city ID.  I think something is wrong in the ETL process where the city ID column in the case table isn't being populated.

![image](https://user-images.githubusercontent.com/2817506/96640720-3329f600-12e9-11eb-9bef-bee12ed94d5c.png)

**Comment by willhwh** [comment]
Fixed by change the index start point to 1 instead of 0.
