### ISSUE TITLE
ETL - Change Null Races to Unknown

### ISSUE THREAD

**Issue by 12wollmana** [12wollmana/UMN-Data_Analytics-Project_02#42]
Currently, when we run into a null race in our ETL process, we fill the value with "no data".  When viewing this in our pie chart, "no data" looks a little odd when compared to the other races.  We should use a better value like "Unknown" instead.

**Comment by 12wollmana** [comment]
![image](https://user-images.githubusercontent.com/2817506/96933673-82f1f400-1486-11eb-9bea-cf2ab10c29af.png)

**Comment by willhwh** [comment]
Added in the "readme" branch.
