### ISSUE TITLE
Visualization Drafts

### ISSUE THREAD

**Issue by 12wollmana** [12wollmana/UMN-Data_Analytics-Project_02#6]
Need to come up with a plan for what visualizations we need to make on the web.

**Comment by richardk6** [comment]
1. Leaflet Map with master clusters
2. Pie Charts for race, class, gender
https://www.amcharts.com/demos/animated-time-line-pie-chart/
3. Bar Graphs - x axis = years. y-axis (number of incidents) and the force used.
https://plotly.com/javascript/bar-charts/#grouped-bar-chart
